# Generated by Django 5.1.2 on 2024-10-26 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_type',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='custom_type',
            name='name',
            field=models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Type 3', 'Type 3')], max_length=55),
        ),
    ]
