# Generated by Django 5.1.2 on 2024-10-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air_Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('air_humidity', models.FloatField()),
            ],
        ),
    ]
