# Generated by Django 5.1.2 on 2024-10-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air_datas', '0001_initial'),
        ('data_detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_data',
            name='data_detection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_detections.data_detection'),
        ),
    ]
