# Generated by Django 5.1.2 on 2024-10-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arduinos', '0001_initial'),
        ('custom_types', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_detection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduinos.arduino')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_types.custom_type')),
            ],
        ),
    ]
