# Generated by Django 5.1.2 on 2024-10-24 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
        ),
    ]
